apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admiral

bases:
  - ../../base

patchesStrategicMerge:
  - envconfig_values.yaml

resources:
  - ns.yaml

resources:
  - ns.yaml

resources:
  - ns.yaml

resources:
  - ns.yaml

resources:
  - ns.yaml


